# Швидкий запуск PostgreSQL через Docker:  docker compose up -d
services:
  postgres:
    image: postgres:17
    container_name: travel-planner-db
    environment:
      POSTGRES_DB: travel_planner
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - travel_planner_data:/var/lib/postgresql/data

volumes:
  travel_planner_data:
